### ISSUE TITLE
.editorconfig is unfriendly to Markdown

### ISSUE THREAD

**Issue by peterkaminski** [Fellowship-of-the-Link/tftmap#3]
In the context of #2, we've added a `.editorconfig` file that includes these settings:

```
indent_style = tab
trim_trailing_whitespace = true
```

`trim_trailing_whitespace` will run afoul of the Markdown syntax for linebreak (two or more trailing spaces), which we commonly use in `Sidebar.md`, and possibly in other files.

We should also discuss our tab preference; it's not clear that tab will be universally preferred.

To clear this issue, discuss the two settings mentioned here, and possibly change them.

**Comment by AramZS** [comment]
So I think generally tabs are better because they are fundamentally more accessible, the developer can manipulate the size of a tab in the way they can't with spaces, allowing users to make it more readable.

I'm not familiar with that particular markdown convention, but legit, hold on, I'll make a change to cover that one before we get in to the tabs v spaces war lol. 

The issue with tabs that I will readily admit is that YAML does not work with them. I haven't seen YAML head metadata in here, so I wasn't sure it was a concern, but I can put in specific rules to cover that case if you plan to use head matter.

**Comment by AramZS** [comment]
@peterkaminski let me know if you need any further changes.

**Comment by peterkaminski** [comment]
@AramZS, I think generally spaces are better because they consistently look the same for everybody, regardless of their tab view settings, even if the developer (or writer) doesn't know about tab view settings. :-)

However, I prefer standardizing over not standardizing, and I don't have too much preference here, so I think we should go with tabs for now and hopefully that will be great.

Thanks for anticipating the potential for YAML frontmatter, there's a decent chance we'll use some.

Checking ~~#3~~ #4  now.

**Comment by AramZS** [comment]
I've done some consideration and research here and there is quite a debate here over how this can work and the question of how to implement "smart_tabs" which is what I have in my own editor. For the sake of ease of use with YAML front matter, I think this is best settled by just using two spaces per tab. I really think tabs are more accessible because of tab view settings, but there is no way of getting around the fact that YAML as a spec defines them as two spaces and will break--usually silently--if they are tabs while the logic to mix the two in one file is going to not be easy to configure for most contributors. I'll make the changes to the PR.

**Comment by peterkaminski** [comment]
Fixed in #4
